In [1]:
import numpy as np

In [3]:
a = np.array([[[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]], [[12, 11, 13, 23], [23, 7, 12, 14], [31, 34, 33, 17]], [[10, 6, 13, 22], [34, 7, 20, 14], [31, 34, 33, 7]]])

In [5]:
np.sort(a, axis= 2, kind=None, order=None) 

array([[[10, 11, 13, 22],
        [ 7, 14, 20, 23],
        [11, 17, 31, 33]],

       [[11, 12, 13, 23],
        [ 7, 12, 14, 23],
        [17, 31, 33, 34]],

       [[ 6, 10, 13, 22],
        [ 7, 14, 20, 34],
        [ 7, 31, 33, 34]]])

In [7]:
np.where(a > 4, a, -1)

array([[[10, 11, 13, 22],
        [23,  7, 20, 14],
        [31, 11, 33, 17]],

       [[12, 11, 13, 23],
        [23,  7, 12, 14],
        [31, 34, 33, 17]],

       [[10,  6, 13, 22],
        [34,  7, 20, 14],
        [31, 34, 33,  7]]])

In [8]:
np.where(a < 5, a, 10*a)

array([[[100, 110, 130, 220],
        [230,  70, 200, 140],
        [310, 110, 330, 170]],

       [[120, 110, 130, 230],
        [230,  70, 120, 140],
        [310, 340, 330, 170]],

       [[100,  60, 130, 220],
        [340,  70, 200, 140],
        [310, 340, 330,  70]]])